config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  draw :admin
  draw :auth
  draw :subdomain
  draw :users

  controller :static do
    get :terms, :privacy, :expired
  end

  root 'static#index'
end

app/views/layouts/_frame.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" dir="ltr" class="navbar-vertical-collapsed">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= ENV['APP_NAME'] %></title>

    <%= favicon_pack_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/png' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_packs_with_chunks_tag 'application' %>
  </head>

  <%= yield %>

</html>

app/views/layouts/application.html.erb
<%= render 'layouts/frame' do %>
  <body>
    <main class="main" id="top">
      <%# 常规页面需要包裹 %>
      <div class="container" data-layout="container">
        <%# 垂直导航 %>
        <%= render 'layouts/application/sidebar' %>

        <div class="content">
          <%# 顶部导航 %>
          <%= render 'layouts/application/navbar' %>
          <%# 面包屑导航 %>
          <%= render 'layouts/application/breadcrumb' %>

          <%= yield %>

          <%= render 'layouts/application/footer' %>
        </div>
      </div>
    </main>

    <%= render 'layouts/common/toast' %>
    <%= render 'layouts/common/modal' %>
  </body>
<% end %>

app/views/layouts/devise.html.erb
<%= render 'layouts/frame' do %>
  <body>
    <main class="main" id="top">
      <div class="container-fluid">
        <div class="row min-vh-100 flex-center no-gutters">
          <div class="col-lg-8 col-xxl-5 py-3">
            <!-- 背景图 -->
            <%= image_pack_tag 'bg-shape.png', class: 'bg-auth-circle-shape', width: 250, alt: '' %>
            <%= image_pack_tag 'shape-1.png', class: 'bg-auth-circle-shape-2', width: 150, alt: '' %>

            <!-- 表单区 开始 -->
            <div class="card overflow-hidden z-index-1">
              <div class="card-body p-0">
                <div class="row no-gutters h-100">
                  <!-- 左侧信息 -->
                  <div class="col-md-5 text-white text-center bg-card-gradient">
                    <div class="position-relative p-4 pt-md-5 pb-md-7">
                      <div class="bg-holder bg-auth-card-shape"></div>

                      <div class="z-index-1 position-relative">
                        <%= link_to ENV['APP_NAME'], root_path, class: 'text-white mb-4 text-sans-serif font-weight-extra-bold fs-4 d-inline-block text-decoration-none' %>
                        <p class="text-white opacity-75">With the power of Falcon, you can now focus only on functionaries for your digital products, while leaving the UI design on us!</p>
                      </div>
                    </div>
                    <div class="mt-3 mb-4 mt-md-4 mb-md-5">
                      <p>
                        还没有账号?<br>
                        <%= link_to '立刻注册', new_user_registration_path, class: 'text-white text-underline' %>
                      </p>

                      <p class="mb-0 mt-4 mt-md-5 fs--1 font-weight-semi-bold text-white opacity-75">
                        <%= link_to "《服务条款》", terms_path, class: 'text-underline text-white' %>
                        和 <%= link_to "《隐私政策》", privacy_path, class: 'text-underline text-white' %>
                      </p>
                    </div>
                  </div>

                  <!-- 右侧表单 -->
                  <div class="col-md-7 d-flex flex-center">
                    <div class="p-4 p-md-5 flex-grow-1">
                      <%= yield %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- 表单区 结束 -->
          </div>
        </div>
      </div>
    </main>
  </body>
<% end %>

app/views/layouts/static.html.erb
<%= render 'layouts/frame' do %>
  <body data-spy="scroll" data-target="#static-scroll">
    <main class="main" id="top">
      <%= render 'layouts/static/navbar' %>
      
      <%= yield %>

      <%= render 'layouts/static/footer' %>
      <%= render 'layouts/common/modal' %>
    </main>
    <%= render 'layouts/common/toast' %>
  </body>
<% end %>